name: Test

on:
  push:
    branches: [main, dev]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-18.04
    container:
      image: swift:5.3
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenSSL
        run: apt-get update && apt-get install -y openssl libssl-dev
      - name: Test CloudyKit
        run: swift test